services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./src:/src:cached
      - ./logs:/src/logs:cached
    restart: always